@ stdcall IoCreateDevice(ptr long ptr long long long ptr)
@ stdcall IoRegisterDriverReinitialization(ptr ptr ptr)
@ stdcall MmPageEntireDriver(ptr)
@ stdcall IoDeleteDevice(ptr)
@ stdcall IoStartPacket(ptr ptr ptr ptr)
@ stdcall IoStartNextPacket(ptr long)
@ stdcall KeInsertDeviceQueue(ptr ptr)
@ stdcall KeInsertByKeyDeviceQueue(ptr ptr long)
@ stdcall KeRemoveDeviceQueue(ptr)
@ stdcall KeRemoveByKeyDeviceQueue(ptr long)
@ stdcall IoAllocateDriverObjectExtension(ptr ptr long ptr)
@ stdcall IoGetDriverObjectExtension(ptr ptr)
@ stdcall IoCreateTimer(ptr)
@ stdcall IoSetTimer(ptr long long ptr ptr)
@ stdcall HalMakeBeep(long)
@ cdecl _assert(str str long)
