@ stdcall IoCreateDevice(ptr long ptr long long long ptr)
@ stdcall MmPageEntireDriver(ptr)
@ stdcall IoDeleteDevice(ptr)
@ stdcall HalMakeBeep(long)
@ stdcall IoStartPacket(ptr ptr ptr ptr)
@ stdcall IoStartNextPacket(ptr long)
@ stdcall KeInitializeTimer(ptr)
@ stdcall KeSetTimer(ptr long long ptr)
@ cdecl _assert(str str long)
