# DllInitialize
@ stdcall ScsiPortMoveMemory(ptr ptr long) StorPortMoveMemory
@ cdecl ScsiPortNotification() StorPortNotification
@ stdcall StorPortAllocateRegistryBuffer(ptr ptr)
@ stdcall StorPortBusy(ptr long)
@ stdcall StorPortCompleteRequest(ptr long long long long)
@ stdcall StorPortConvertPhysicalAddressToUlong(long long)
@ stdcall StorPortConvertUlongToPhysicalAddress(long)
@ varargs StorPortDebugPrint(long str)
@ stdcall StorPortDeviceBusy(ptr long long long long)
@ stdcall StorPortDeviceReady(ptr long long long)
@ cdecl StorPortExtendedFunction()
@ stdcall StorPortFreeDeviceBase(ptr ptr)
@ stdcall StorPortFreeRegistryBuffer(ptr ptr)
@ stdcall StorPortGetBusData(ptr long long long ptr long)
@ stdcall StorPortGetDeviceBase(ptr long long long long long long)
@ stdcall StorPortGetLogicalUnit(ptr long long long)
@ stdcall StorPortGetPhysicalAddress(ptr ptr ptr long)
@ stdcall StorPortGetScatterGatherList(ptr ptr)
@ stdcall StorPortGetSrb(ptr long long long long)
@ stdcall StorPortGetUncachedExtension(ptr ptr long)
@ stdcall StorPortGetVirtualAddress(ptr long long)
@ stdcall StorPortInitialize(ptr ptr ptr ptr)
@ stdcall StorPortLogError(ptr ptr long long long long long)
@ stdcall StorPortMoveMemory(ptr ptr long)
@ cdecl StorPortNotification()
@ stdcall StorPortPause(ptr long)
@ stdcall StorPortPauseDevice(ptr long long long long)
@ stdcall StorPortQuerySystemTime(ptr)
@ stdcall StorPortReady(ptr)
@ stdcall StorPortRegistryRead(ptr ptr long long ptr ptr)
@ stdcall StorPortRegistryWrite(ptr ptr long long ptr long)
@ stdcall StorPortResume(ptr)
@ stdcall StorPortResumeDevice(ptr long long long)
@ stdcall StorPortSetBusDataByOffset(ptr long long long ptr long long)
@ stdcall StorPortSetDeviceQueueDepth(ptr long long long long)
@ stdcall StorPortStallExecution(long)
@ stdcall StorPortSynchronizeAccess(ptr ptr ptr)
@ stdcall StorPortValidateRange(ptr long long long long long long)
@ stdcall StorPortAllocateDmaMemory(ptr ptr long long long long long long long long ptr ptr)
@ stdcall StorPortFreeDmaMemory(ptr ptr ptr long long long)
@ stdcall ScsiPortWmiDispatchFunction(ptr long ptr ptr ptr long ptr)
@ stdcall ScsiPortWmiPostProcess(ptr long long)
