@ stdcall IoCreateDevice(ptr long ptr long int64 long ptr)
@ stdcall IoCreateStreamFileObject(ptr)
@ stdcall IoRegisterDriverReinitialization(ptr ptr ptr)
@ stdcall IoAllocateDriverObjectExtension(ptr ptr long ptr)
@ stdcall IoRegisterFileSystem(ptr)
@ stdcall IoGetDriverObjectExtension(ptr ptr)
@ stdcall IoGetDeviceObjectPointer(ptr long ptr ptr)
@ stdcall IoAttachDeviceToDeviceStack(ptr ptr)
@ stdcall IoGetAttachedDeviceReference(ptr)
@ stdcall IoRegisterDeviceInterface(ptr ptr ptr ptr)
@ stdcall IoSetDeviceInterfaceState(ptr long)
@ stdcall IoGetDeviceInterfaces(ptr ptr long ptr)
@ stdcall IoGetDeviceProperty(ptr long long ptr ptr)
@ stdcall IoGetDevicePropertyData(ptr ptr long long long ptr ptr ptr)
@ stdcall IoCreateSymbolicLink(ptr ptr)
@ stdcall IoDeleteSymbolicLink(ptr)
@ stdcall IoOpenDeviceRegistryKey(ptr long long ptr)
@ stdcall IoQueryDeviceDescription(ptr ptr ptr ptr ptr ptr ptr ptr)
@ stdcall IoDetachDevice(ptr)
@ stdcall IoDeleteDevice(ptr)
@ stdcall IoInvalidateDeviceRelations(ptr long)
@ stdcall IoReportTargetDeviceChangeAsynchronous(ptr ptr ptr ptr)
@ stdcall IoStartPacket(ptr ptr ptr ptr)
@ stdcall IoStartNextPacket(ptr long)
@ stdcall IoBuildPartialMdl(ptr ptr long)
@ stdcall IoAllocateMdl(ptr long)
@ stdcall IoBuildDeviceIoControlRequest(long ptr ptr long ptr long long ptr)
@ stdcall IoBuildAsynchronousFsdRequest(long ptr ptr long ptr ptr)
@ stdcall IoBuildSynchronousFsdRequest(long ptr ptr long ptr ptr ptr)
@ stdcall IoCallDriver(ptr ptr)
@ stdcall IoForwardIrpSynchronously(ptr ptr)
@ stdcall IoCompleteRequest(ptr long)
@ stdcall IoCancelIrp(ptr)
@ stdcall IoReuseIrp(ptr long)
@ stdcall IoFreeIrp(ptr)
@ stdcall IoConnectInterrupt(ptr ptr ptr long long long long long long long)
@ stdcall IoDisconnectInterrupt(ptr)
@ stdcall IoAllocateWorkItem(ptr)
@ stdcall IoInitializeWorkItem(ptr ptr)
@ stdcall IoFreeWorkItem(ptr)
@ stdcall IoQueueWorkItem(ptr ptr long ptr)
@ stdcall IoQueueWorkItemEx(ptr ptr long ptr)
@ stdcall IoAcquireInterruptMutex(ptr)
@ stdcall IoReleaseInterruptMutex(ptr long)
@ stdcall IoGetConfigurationInformation()
@ stdcall IoReadPciConfigSpace(ptr ptr long ptr)
@ stdcall IoWritePciConfigSpace(ptr ptr long ptr)
@ stdcall IoReadPartitionTable(ptr long long ptr)
@ stdcall IoReadPartitionTableEx(ptr ptr)
@ stdcall IoWritePartitionTable(ptr long long long ptr)
@ stdcall IoWritePartitionTableEx(ptr ptr)
@ stdcall IoSetPartitionInformation(ptr long long long)
@ stdcall IoSetPartitionInformationEx(ptr long ptr)
@ stdcall IoReadDiskSignature(ptr long ptr)
@ stdcall IoCreateDisk(ptr ptr)
@ stdcall IoRegisterPlugPlayNotification(long long ptr ptr ptr ptr ptr)
@ stdcall IoAllocateErrorLogEntry(ptr long)
@ stdcall IoWriteErrorLogEntry(ptr)
@ stdcall IoEnablePort(long long)
@ stdcall IoWMIRegistrationControl(ptr long)
@ stdcall IoWMIDeviceObjectToProviderId(ptr)
@ stdcall IoWMIWriteEvent(ptr)
@ stdcall IoWMIOpenBlock(ptr long ptr)
@ stdcall IoWMIQueryAllData(ptr ptr ptr)
@ stdcall EtwRegister(ptr ptr ptr ptr)
@ stdcall EtwUnregister(long long)
@ stdcall EtwWrite(long long ptr ptr long ptr)
@ stdcall PoSetPowerState(ptr long long)
@ stdcall PoRequestPowerIrp(ptr long long ptr ptr ptr)
@ stdcall PoRegisterPowerSettingCallback(ptr ptr ptr ptr ptr)
@ stdcall PoUnregisterPowerSettingCallback(ptr)
@ stdcall PoQueryWatchdogTime(ptr ptr)
@ stdcall MmPageEntireDriver(ptr)
@ stdcall MmMapIoSpace(long long long long)
@ stdcall MmUnmapIoSpace(ptr long)
@ stdcall MmAllocateContiguousMemorySpecifyCache(long long long long long long ptr ptr)
@ stdcall MmFreeContiguousMemorySpecifyCache(ptr ptr long)
@ stdcall MmGetPhysicalAddress(ptr)
@ stdcall MmGetVirtualForPhysical(long long)
@ stdcall KeInsertDeviceQueue(ptr ptr)
@ stdcall KeInsertByKeyDeviceQueue(ptr ptr long)
@ stdcall KeRemoveDeviceQueue(ptr)
@ stdcall KeRemoveByKeyDeviceQueue(ptr long)
@ stdcall KeRemoveEntryDeviceQueue(ptr ptr)
@ stdcall KeInitializeDpc(ptr ptr ptr)
@ stdcall KeInsertQueueDpc(ptr ptr ptr)
@ stdcall KeInitializeTimer(ptr)
@ stdcall KeSetTimer(ptr long long ptr)
@ stdcall KeSetTimerEx(ptr long long long ptr)
@ stdcall KeSetLowPriorityTimer(ptr long long long ptr ptr ptr)
@ stdcall KeCancelTimer(ptr)
@ stdcall KeQueryInterruptTime()
@ stdcall KeQuerySystemTime(ptr)
@ stdcall KeQueryTickCount(ptr)
@ stdcall KeQueryTimeIncrement()
@ stdcall KeDelayExecutionThread(long ptr)
@ stdcall KeStallExecutionProcessor(long)
@ stdcall KeInitializeEvent(ptr long long)
@ stdcall KeSetEvent(ptr)
@ stdcall KeResetEvent(ptr)
@ stdcall KeClearEvent(ptr)
@ stdcall KeWaitForSingleObject(ptr long long long ptr)
@ stdcall -arch=arm64 KeFlushIoBuffers(ptr long long)
@ stdcall ObReferenceObject(ptr)
@ stdcall ObDereferenceObject(ptr)
@ stdcall ExAllocatePoolWithTag(long ptr long)
@ stdcall ExFreePoolWithTag(ptr long)
@ stdcall HalMakeBeep(long)
@ stdcall HalGetAdapter(ptr ptr)
@ stdcall HalExamineMBR(ptr long long ptr)
@ stdcall CcInitializeCacheMap(ptr)
@ stdcall CcUninitializeCacheMap(ptr ptr)
@ stdcall CcMapData(ptr ptr long long ptr ptr ptr)
@ stdcall CcSetDirtyData(ptr)
@ stdcall CcUnpinData(ptr)
@ stdcall CcCopyRead(ptr ptr long long ptr ptr)
@ stdcall CcCopyWrite(ptr ptr long long ptr ptr)
@ stdcall CcMdlRead(ptr ptr long ptr ptr)
@ stdcall CcSetFileSizes(ptr ptr)
@ stdcall CcFlushCache(ptr ptr long ptr)
@ stdcall FsRtlDoesNameContainWildCards(ptr)
@ stdcall FsRtlIsNameInExpression(ptr ptr long wstr)
@ stdcall FsRtlAreNamesEqual(ptr ptr long wstr)
@ cdecl -arch=i386,x86_64 __inbyte(long)
@ cdecl -arch=i386,x86_64 __outbyte(long long)
@ cdecl -arch=i386,x86_64 __inword(long)
@ cdecl -arch=i386,x86_64 __outword(long long)
@ cdecl -arch=i386,x86_64 __indword(long)
@ cdecl -arch=i386,x86_64 __outdword(long long)
@ cdecl _assert(str str long)
@ extern InitSafeBootMode
