#pragma once

typedef LONG NTSTATUS;
typedef NTSTATUS *PNTSTATUS;

#define STATUS_SUCCESS                    ((NTSTATUS)0x00000000)

#define STATUS_SEVERITY_SUCCESS         0x0
#define STATUS_SEVERITY_INFORMATIONAL   0x1
#define STATUS_SEVERITY_WARNING         0x2
#define STATUS_SEVERITY_ERROR           0x3
#define ERROR_SEVERITY_SUCCESS		0x00000000
#define ERROR_SEVERITY_INFORMATIONAL	0x40000000
#define ERROR_SEVERITY_WARNING		0x80000000
#define ERROR_SEVERITY_ERROR		0xC0000000
/* Status is success if and only if highest bit is zero */
#define NT_SUCCESS(Status)	(((NTSTATUS)(Status)) >= 0)
#define NT_INFORMATION(Status) (((ULONG)(Status) >> 30) == STATUS_SEVERITY_INFORMATIONAL)
#define NT_WARNING(Status)	(((ULONG)(Status) >> 30) == STATUS_SEVERITY_WARNING)
#define NT_ERROR(Status)	(((ULONG)(Status) >> 30) == STATUS_SEVERITY_ERROR)

#define STATUS_INVALID_PARAMETER		((NTSTATUS)0xC000000DL)
#define STATUS_NO_MEMORY			((NTSTATUS)0xC0000017L)
#define STATUS_OBJECT_NAME_NOT_FOUND		((NTSTATUS)0xC0000034L)
#define STATUS_OBJECT_PATH_SYNTAX_BAD		((NTSTATUS)0xC000003BL)
#define STATUS_INSUFFICIENT_RESOURCES		((NTSTATUS)0xC000009AL)
#define STATUS_INVALID_IMAGE_FORMAT		((NTSTATUS)0xC000007BL)
#define STATUS_NAME_TOO_LONG			((NTSTATUS)0xC0000106L)
#define STATUS_INVALID_IMAGE_NE_FORMAT		((NTSTATUS)0xC000011BL)
#define STATUS_INVALID_IMAGE_LE_FORMAT		((NTSTATUS)0xC000012EL)
#define STATUS_INVALID_IMAGE_NOT_MZ		((NTSTATUS)0xC000012FL)
#define STATUS_INVALID_IMAGE_PROTECT		((NTSTATUS)0xC0000130L)
#define STATUS_INVALID_IMAGE_WIN_16		((NTSTATUS)0xC0000131L)
#define STATUS_INVALID_IMAGE_WIN_32		((NTSTATUS)0xC0000359L)
#define STATUS_INVALID_IMAGE_WIN_64		((NTSTATUS)0xC000035AL)
