#pragma once

#include <kernel/gen_config.h>

#define RTLP_DBGTRACE_MODULE_NAME	"NTOS"

#include <nt.h>
#include <assert.h>
#include <compile_assert.h>
#include <string.h>
#include <gnu.h>
#include <debug.h>
#include <image.h>
#include <util.h>

#include "ntosdef.h"
#include "ke.h"
#include "mm.h"
#include "ex.h"
#include "ob.h"
#include "io.h"
#include "cm.h"
#include "ps.h"
#include "ldr.h"
#include "rtl.h"
#include "hal.h"

/* Generated by syssvc-gen.py */
#include <ntos_syssvc_gen.h>
#include <ntos_wdmsvc_gen.h>

#ifdef CONFIG_DEBUG_BUILD
VOID MmDbgDumpCapTreeNode(IN PCAP_TREE_NODE Node);
VOID MmDbgDumpCNode(IN PCNODE CNode);
VOID MmDbgDumpUntypedInfo();
VOID MmDbgDumpPagingStructure(IN PPAGING_STRUCTURE Paging);
VOID MmDbgDumpPagingStructureRecursively(IN PPAGING_STRUCTURE Paging);
VOID MmDbgDumpSection(IN PSECTION Section);
VOID MmDbgDumpVad(PMMVAD Vad);
VOID MmDbgDumpVSpace(PVIRT_ADDR_SPACE VSpace);
VOID IoDbgDumpFileObject(IN PIO_FILE_OBJECT File);
#else
#define MmDbgDumpCapTreeNode(x)
#define MmDbgDumpCNode(x)
#define MmDbgDumpUntypedInfo()
#define MmDbgDumpPagingStructure(x)
#define MmDbgDumpPagingStructureRecursively(x)
#define MmDbgDumpSection(x)
#define MmDbgDumpVad(x)
#define MmDbgDumpVSpace(x)
#define IoDbgDumpFileObject(x)
#endif
