#pragma once

typedef enum _OBJECT_TYPE_ENUM {
				OBJECT_TYPE_DIRECTORY,
				OBJECT_TYPE_THREAD,
				OBJECT_TYPE_PROCESS,
				OBJECT_TYPE_SECTION,
				NUM_OBJECT_TYPES
} OBJECT_TYPE_ENUM;

typedef struct _OBJECT_TYPE {
    OBJECT_TYPE_ENUM TypeEnum;
    UNICODE_STRING Name;
    SIZE_T NumCaps;		/* Number of capabilities in ObjectData */
    struct _OBJECT_TYPE_INITIALIZER *Init;
} OBJECT_TYPE, *POBJECT_TYPE;

typedef struct _OBJECT_HEADER {
    POBJECT_TYPE Type;
    MWORD HandleCount;
    PHANDLE Handles;
} OBJECT_HEADER, *POBJECT_HEADER;

typedef NTSTATUS (*OB_TYPE_CREATE_METHOD)(POBJECT_TYPE);
typedef NTSTATUS (*OB_OBJECT_OPEN_METHOD)(POBJECT_HEADER);
typedef NTSTATUS (*OB_OBJECT_CLOSE_METHOD)(POBJECT_HEADER);

typedef struct _OBJECT_TYPE_INITIALIZER {
    OB_TYPE_CREATE_METHOD TypeCreateProc;
    OB_OBJECT_OPEN_METHOD OpenProc;
    OB_OBJECT_CLOSE_METHOD CloseProc;
} OBJECT_TYPE_INITIALIZER, *POBJECT_TYPE_INITIALIZER;

NTSTATUS ObCreateObjectType(IN OBJECT_TYPE_ENUM Type,
			    IN PCWSTR TypeName,
			    IN POBJECT_TYPE_INITIALIZER Init);
